name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
      - shell: bash
        run: |
          curl -sL https://deno.land/x/edcb@v0.4.1/edcb.sh > ~/ecli
          chmod +x ~/ecli
          PATH=$PATH:~/ecli
          deno run -A cli.ts
